In [2]:
import torch
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
print(x.shape)
print(x.numel())


torch.Size([12])
12


In [7]:
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
print(torch.zeros((2,3,4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [10]:
print(torch.ones((2,3,4)))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [13]:
#标准高斯分布
print(torch.randn(3,4))
print(torch.normal(0,1,[3,4]))

tensor([[-0.8807, -1.2655,  0.8197, -0.7575],
        [ 0.7466, -0.8742,  0.2354,  0.9069],
        [-0.1619, -0.6741, -1.7797,  0.1150]])
tensor([[ 1.4993,  1.2785,  0.2028,  0.6900],
        [ 0.6235, -0.6850, -0.3774, -0.2426],
        [ 2.3807,  0.3116, -1.4807, -1.4629]])
