In [2]:
import torch
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
print(x.shape)
print(x.numel())


torch.Size([12])
12


In [7]:
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
print(torch.zeros((2,3,4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [10]:
print(torch.ones((2,3,4)))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [13]:
#标准高斯分布
print(torch.randn(3,4))
print(torch.normal(0,1,[3,4]))

tensor([[-0.8807, -1.2655,  0.8197, -0.7575],
        [ 0.7466, -0.8742,  0.2354,  0.9069],
        [-0.1619, -0.6741, -1.7797,  0.1150]])
tensor([[ 1.4993,  1.2785,  0.2028,  0.6900],
        [ 0.6235, -0.6850, -0.3774, -0.2426],
        [ 2.3807,  0.3116, -1.4807, -1.4629]])


In [17]:
print(torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]]))


tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


## 运算

In [22]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])\n

In [24]:
print(torch.exp(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [25]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1,4,3],[1,2,3,4],[4,3,2,1]])
print(torch.cat((X,Y),dim=0))
print(torch.cat((X,Y),dim=1))


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [26]:
print(X==Y)


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [27]:
print(X.sum())
print(X.mean())

tensor(66.)
tensor(5.5000)


## 广播机制
在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。这种机制的工作方式如下：首先，通过适当复制元素来扩展一个或两个数组， 以便在转换之后，两个张量具有相同的形状。 其次，对生成的数组执行按元素操作。

In [28]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a,b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


In [29]:
print(a+b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 索引和切片

In [31]:
print(X[-1])
print(X[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [33]:
X[0:2,:] = 2
print(X)


tensor([[ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.],
        [ 8.,  9., 10., 11.]])


## 节省内存

In [34]:
before = id(Y)
Y = Y + X
id(Y) == before


False

In [35]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))


id(Z): 1813108235064
id(Z): 1813108235064


In [36]:
before = id(X)
X += Y
id(X) == before


True