## 标量

In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)


tensor(5.)
tensor(1.)
tensor(6.)
tensor(1.5000)
tensor(9.)


## 向量


In [2]:
x = torch.arange(4)
print(x)


tensor([0, 1, 2, 3])


In [3]:
print(x[3])


tensor(3)


In [4]:
print(len(x))


4


In [5]:
print(x.shape)


torch.Size([4])


## 矩阵

In [6]:
A = torch.arange(20).reshape(5,4)
print(A)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


转置

In [7]:
print(A.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [8]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


In [9]:
#对称矩阵
print(B==B.T)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [10]:
X = torch.arange(24).reshape(2,3,4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [13]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()   #通过分配新内存，将A的一个副本分配给B
print(A)
print(A+B)
print(A*B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [14]:
a = 2
X = torch.arange(24).reshape(2,3,4)
print(a+X)
print((a*X).shape)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


## 降维

In [18]:
x = torch.arange(4, dtype=torch.float32)
print(x)
print(x.sum())
print(A.sum())

tensor([0., 1., 2., 3.])
tensor(6.)
tensor(190.)


沿着某个轴求和

In [19]:
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0,A_sum_axis0.shape)
print(A.sum(axis=[0,1]))

tensor([40., 45., 50., 55.]) torch.Size([4])
tensor(190.)


In [20]:
print(A.mean(), A.sum() / A.numel())


tensor(9.5000) tensor(9.5000)


In [24]:
sum_A = A.sum(axis=1, keepdims=True)  #求和后任保持维度不变
print(sum_A)
print(sum_A.shape)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])


In [25]:
#这样就可以利用广播机制
print(A / sum_A)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
