In [7]:
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l


In [8]:
fair_probs = torch.ones([6]) / 6    #骰子每一面出现的概率
multinomial.Multinomial(1, fair_probs).sample()  #投骰子这个动作,第一个参数是次数，第二个是概率

tensor([0., 0., 0., 1., 0., 0.])

In [9]:
multinomial.Multinomial(10, fair_probs).sample()


tensor([2., 1., 1., 4., 1., 1.])

In [10]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # 相对频率作为估计值


tensor([0.1590, 0.1450, 0.1810, 0.1790, 0.1630, 0.1730])

In [11]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)

# d2l.set_figsize((6, 4.5))
# for i in range(6):
#     d2l.plt.plot(estimates[:, i].numpy(),
#                  label=("P(die=" + str(i + 1) + ")"))
# d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
# d2l.plt.gca().set_xlabel('Groups of experiments')
# d2l.plt.gca().set_ylabel('Estimated probability')
# d2l.plt.legend();

In [14]:
print(counts)
print(cum_counts)


tensor([[1., 2., 0., 3., 1., 3.],
        [1., 1., 2., 1., 5., 0.],
        [0., 2., 2., 3., 3., 0.],
        ...,
        [0., 3., 1., 2., 2., 2.],
        [2., 3., 0., 1., 3., 1.],
        [2., 1., 2., 0., 4., 1.]])
tensor([[  1.,   2.,   0.,   3.,   1.,   3.],
        [  2.,   3.,   2.,   4.,   6.,   3.],
        [  2.,   5.,   4.,   7.,   9.,   3.],
        ...,
        [780., 863., 818., 818., 860., 841.],
        [782., 866., 818., 819., 863., 842.],
        [784., 867., 820., 819., 867., 843.]])
