In [1]:
import torch
import torch.nn.functional as F
from torch import  nn

## 不带参数的层

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X - X.mean()


In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))


tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [5]:
Y= net(torch.rand(4,8))
print(Y.mean())


tensor(-7.4506e-09, grad_fn=<MeanBackward0>)


## 带参数的层

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)


In [8]:
linear = MyLinear(5, 3)
linear.weight


Parameter containing:
tensor([[ 9.5338e-02, -9.7824e-01, -4.1812e-01],
        [ 1.5153e+00,  6.7932e-01, -1.2614e-05],
        [-5.7620e-01,  2.6021e+00, -3.0190e-01],
        [ 2.4339e-01, -5.3668e-01,  1.8677e+00],
        [-9.5850e-01, -3.8041e-01, -6.2749e-01]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5))


tensor([[1.1914, 0.1266, 0.0000],
        [1.2535, 0.7372, 0.0000]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))


tensor([[12.0180],
        [ 9.2891]])