In [1]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

## 初始化参数

In [2]:
num_inputs = 784  #28*28
num_output = 10
W = torch.normal(0,0.01,size=[num_inputs,num_output],requires_grad=True)
b = torch.zeros(num_output,requires_grad=True)

## 定义softmax函数

In [3]:
def softmax(X):
    X_exp = torch.exp(X)    #size = [x,y]
    partition = X_exp.sum(1, keepdim=True) #按列求和 #size = [1,y]
    return X_exp/partition #利用了广播机制  size = [x,y]

In [4]:
#测试softmax函数
X = torch.normal(0,1,(2,5))
X_prob = softmax(X)
print(X_prob, X_prob.sum(1))

tensor([[0.1844, 0.0880, 0.0964, 0.5359, 0.0952],
        [0.0870, 0.0718, 0.2409, 0.0487, 0.5515]]) tensor([1., 1.])


# 定义模型线性回归
y = soft(WX+b)

In [ ]:
def net(X):
    return softmax(torch.matmul(torch.reshape(X,(-1,X.shape[0])),W)+b)

In [14]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]  #返回[0,0] [1,2]两个位置的数据

tensor([0.1000, 0.5000])

In [16]:
#返回预测的真实标签类的交叉熵损失
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y])
cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])

## 分类的准确率计算

In [ ]:
def accuracy(y_hat, y):  #@save
    """计算预测正确的数量"""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())

In [18]:
accuracy(y_hat, y) / len(y)


0.5